// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW0okgj9XlwySRUFyWOgjHle3kRNFpTvA',
    appId: '1:837795540756:web:adb52d6dcafcfb14701c01',
    messagingSenderId: '837795540756',
    projectId: 'gutsy-d3632',
    authDomain: 'gutsy-d3632.firebaseapp.com',
    storageBucket: 'gutsy-d3632.firebasestorage.app',
    measurementId: 'G-QVN74QP2Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRnD-d8LI5lTnNR4pVYSjQfXIhhk_7chI',
    appId: '1:837795540756:android:175758224e78f857701c01',
    messagingSenderId: '837795540756',
    projectId: 'gutsy-d3632',
    storageBucket: 'gutsy-d3632.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYDPp_fK0D-8WoPkLKvPP19Vt16ju5Wd0',
    appId: '1:837795540756:ios:44eb7c010703c0a5701c01',
    messagingSenderId: '837795540756',
    projectId: 'gutsy-d3632',
    storageBucket: 'gutsy-d3632.firebasestorage.app',
    iosBundleId: 'com.example.gutsyx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYDPp_fK0D-8WoPkLKvPP19Vt16ju5Wd0',
    appId: '1:837795540756:ios:44eb7c010703c0a5701c01',
    messagingSenderId: '837795540756',
    projectId: 'gutsy-d3632',
    storageBucket: 'gutsy-d3632.firebasestorage.app',
    iosBundleId: 'com.example.gutsyx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW0okgj9XlwySRUFyWOgjHle3kRNFpTvA',
    appId: '1:837795540756:web:8d260dc2ae18de5a701c01',
    messagingSenderId: '837795540756',
    projectId: 'gutsy-d3632',
    authDomain: 'gutsy-d3632.firebaseapp.com',
    storageBucket: 'gutsy-d3632.firebasestorage.app',
    measurementId: 'G-TBB3GBCRHN',
  );
}
