// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_WEB'),
    appId: String.fromEnvironment('FIREBASE_APP_ID_WEB'),
    messagingSenderId: '837795540756',
    projectId: 'gutsy-d3632',
    authDomain: 'gutsy-d3632.firebaseapp.com',
    storageBucket: 'gutsy-d3632.firebasestorage.app',
    measurementId: 'G-QVN74QP2Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_ANDROID'),
    appId: String.fromEnvironment('FIREBASE_APP_ID_ANDROID'),
    messagingSenderId: '837795540756',
    projectId: 'gutsy-d3632',
    storageBucket: 'gutsy-d3632.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_IOS'),
    appId: String.fromEnvironment('FIREBASE_APP_ID_IOS'),
    messagingSenderId: '837795540756',
    projectId: 'gutsy-d3632',
    storageBucket: 'gutsy-d3632.firebasestorage.app',
    iosBundleId: 'com.example.gutsyx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_IOS'),
    appId: String.fromEnvironment('FIREBASE_APP_ID_IOS'),
    messagingSenderId: '837795540756',
    projectId: 'gutsy-d3632',
    storageBucket: 'gutsy-d3632.firebasestorage.app',
    iosBundleId: 'com.example.gutsyx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_WEB'),
    appId: String.fromEnvironment('FIREBASE_APP_ID_WEB_WINDOWS'),
    messagingSenderId: '837795540756',
    projectId: 'gutsy-d3632',
    authDomain: 'gutsy-d3632.firebaseapp.com',
    storageBucket: 'gutsy-d3632.firebasestorage.app',
    measurementId: 'G-TBB3GBCRHN',
  );
}
